spring.application.name=vehicletoll

# Configuração de conexão do H2 simulando o comportamento e sintaxe do MySQL (MODE=MySQL)
spring.datasource.url=jdbc:h2:mem:vehicletolldb;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuração do Hibernate/JPA
# update: O Spring vai criar as tabelas no banco de forma automática baseado no nosso código Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilita o painel do H2 no navegador para podermos ver as tabelas criadas
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
